// <auto-generated />
using System;
using DefaultNamespace;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dataaccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507110221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dataaccess.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("dataaccess.Entities.TelemetryReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BuzzerActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeviceIdFk")
                        .HasColumnType("integer");

                    b.Property<int>("GasAnalogValue")
                        .HasColumnType("integer");

                    b.Property<int>("GasBaseline")
                        .HasColumnType("integer");

                    b.Property<bool>("GasDangerDetected")
                        .HasColumnType("boolean");

                    b.Property<int>("GasDangerThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("GasDigitalValue")
                        .HasColumnType("integer");

                    b.Property<double>("HumidityPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("PressureHpa")
                        .HasPrecision(7, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureC")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<long>("TimestampUnix")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("DeviceIdFk", "TimestampUtc");

                    b.ToTable("TelemetryReadings");
                });

            modelBuilder.Entity("dataaccess.Entities.TelemetryReading", b =>
                {
                    b.HasOne("dataaccess.Entities.Device", "Device")
                        .WithMany("TelemetryReadings")
                        .HasForeignKey("DeviceIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("dataaccess.Entities.Device", b =>
                {
                    b.Navigation("TelemetryReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
